"""Load curated Phase 1 opportunities (Banking, SSC, State PSC)."""

from datetime import date

from app.db import Base, SessionLocal, engine
from app.models import Opportunity

SEED = [
    {
        "canonical_title": "IBPS CRP PO/MT-XVI 2026",
        "org_name": "Institute of Banking Personnel Selection",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Banking",
        "education_required": ["Any Graduate", "Graduate"],
        "stream_required": None,
        "min_percentage": None,
        "age_min": 20,
        "age_max": 30,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10, "ExServicemen": "as per rules"},
        "age_cutoff_date": date(2026, 8, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "certifications_required": None,
        "prerequisite_exams": None,
        "experience_required_years": None,
        "category_vacancies": {"General": 1400, "OBC": 900, "SC": 500, "ST": 250, "EWS": 350},
        "notified_at": date(2026, 7, 1),
        "apply_start_date": date(2026, 8, 1),
        "apply_end_date": date(2026, 9, 21),
        "exam_date": date(2026, 10, 18),
        "exam_stage": "Prelims",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 850, "OBC": 850, "SC": 175, "ST": 175},
        "primary_source_url": "https://www.ibps.in/",
        "raw_notification_text": "IBPS invites online applications for CRP PO/MT-XVI. Graduation in any discipline. Age 20-30 as on 01.08.2026.",
        "pdf_url": "https://www.ibps.in/",
        "extraction_confidence": 1.0,
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "SBI Clerk (Junior Associate) 2026",
        "org_name": "State Bank of India",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Banking",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 20,
        "age_max": 28,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10},
        "age_cutoff_date": date(2026, 4, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "category_vacancies": {"General": 2000, "OBC": 1200, "SC": 700, "ST": 350, "EWS": 500},
        "notified_at": date(2026, 3, 15),
        "apply_start_date": date(2026, 4, 1),
        "apply_end_date": date(2026, 9, 10),
        "exam_date": date(2026, 11, 2),
        "exam_stage": "Prelims",
        "status": "ClosingSoon",
        "fee_structure": {"General": 750, "OBC": 750, "SC": 125, "ST": 125},
        "primary_source_url": "https://sbi.co.in/web/careers",
        "raw_notification_text": "SBI Junior Associate recruitment. Graduation required. Age 20-28.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "SSC Combined Graduate Level (CGL) 2026",
        "org_name": "Staff Selection Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "SSC",
        "education_required": ["Any Graduate", "Graduate", "B.A.", "B.Sc", "B.Com"],
        "age_min": 18,
        "age_max": 32,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10},
        "age_cutoff_date": date(2026, 8, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "category_vacancies": {"General": 4000, "OBC": 2500, "SC": 1400, "ST": 700, "EWS": 900},
        "notified_at": date(2026, 6, 10),
        "apply_start_date": date(2026, 6, 24),
        "apply_end_date": date(2026, 9, 25),
        "exam_date": date(2026, 12, 5),
        "exam_stage": "Prelims",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 100, "OBC": 100, "SC": 0, "ST": 0},
        "primary_source_url": "https://ssc.gov.in/",
        "raw_notification_text": "SSC CGL 2026. Bachelor's degree from a recognised university. Age 18-32.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "SSC CHSL 2026 (10+2)",
        "org_name": "Staff Selection Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "SSC",
        "education_required": ["12th", "Diploma", "Graduate", "Postgraduate"],
        "age_min": 18,
        "age_max": 27,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 1, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "certifications_required": ["Typing 35wpm"],
        "category_vacancies": {"General": 1800, "OBC": 1100, "SC": 600, "ST": 300, "EWS": 400},
        "apply_start_date": date(2026, 5, 1),
        "apply_end_date": date(2026, 9, 30),
        "exam_date": date(2026, 11, 15),
        "exam_stage": "Tier-I",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 100, "OBC": 100, "SC": 0, "ST": 0},
        "primary_source_url": "https://ssc.gov.in/",
        "raw_notification_text": "SSC CHSL. 12th pass. Typing 35 wpm in English required for DEO/LDC posts.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "RRB NTPC Graduate 2026",
        "org_name": "Railway Recruitment Board",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Railway",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 18,
        "age_max": 33,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 7, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "category_vacancies": {"General": 3500, "OBC": 2200, "SC": 1200, "ST": 600, "EWS": 800},
        "apply_start_date": date(2026, 7, 15),
        "apply_end_date": date(2026, 10, 14),
        "exam_stage": "CBT-1",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 500, "OBC": 500, "SC": 250, "ST": 250},
        "primary_source_url": "https://indianrailways.gov.in/",
        "raw_notification_text": "RRB NTPC graduate posts. Age 18-33.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "UPPSC Combined State / Upper Subordinate Services 2026",
        "org_name": "Uttar Pradesh Public Service Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "State-PSC",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 21,
        "age_max": 40,
        "age_relaxation_rules": {"OBC": 5, "SC": 5, "ST": 5, "PwD": 15},
        "age_cutoff_date": date(2026, 7, 1),
        "gender_restriction": "Any",
        "domicile_required": "Uttar Pradesh",
        "category_vacancies": {"General": 80, "OBC": 50, "SC": 35, "ST": 8, "EWS": 20},
        "apply_start_date": date(2026, 6, 1),
        "apply_end_date": date(2026, 9, 18),
        "exam_date": date(2026, 12, 20),
        "exam_stage": "Prelims",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 125, "OBC": 125, "SC": 65, "ST": 65},
        "primary_source_url": "https://uppsc.up.nic.in/",
        "raw_notification_text": "UPPSC PCS 2026. Graduation. Domicile of Uttar Pradesh required. Age 21-40.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "UPSC Civil Services (Prelims) 2027",
        "org_name": "Union Public Service Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "UPSC-CSE",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 21,
        "age_max": 32,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5, "PwD": 10},
        "age_cutoff_date": date(2027, 8, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "apply_start_date": date(2027, 2, 1),
        "apply_end_date": date(2027, 3, 21),
        "exam_date": date(2027, 5, 24),
        "exam_stage": "Prelims",
        "status": "Upcoming",
        "fee_structure": {"General": 100, "OBC": 100, "SC": 0, "ST": 0},
        "primary_source_url": "https://upsc.gov.in/",
        "raw_notification_text": "UPSC CSE Prelims 2027. Degree from a recognised university.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "UPSC Civil Services (Mains) 2026 — qualified candidates only",
        "org_name": "Union Public Service Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "UPSC-CSE",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 21,
        "age_max": 32,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 8, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "prerequisite_exams": [{"exam": "UPSC Prelims", "year_validity": "same year"}],
        "apply_start_date": date(2026, 7, 1),
        "apply_end_date": date(2026, 9, 15),
        "exam_date": date(2026, 9, 20),
        "exam_stage": "Mains",
        "status": "ApplicationsOpen",
        "primary_source_url": "https://upsc.gov.in/",
        "raw_notification_text": "Only candidates who cleared UPSC Prelims 2026 may appear for Mains.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "IBPS Clerk CRP-XV 2026",
        "org_name": "Institute of Banking Personnel Selection",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Banking",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 20,
        "age_max": 28,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 7, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "apply_start_date": date(2026, 7, 1),
        "apply_end_date": date(2026, 9, 28),
        "exam_stage": "Prelims",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 850, "OBC": 850, "SC": 175, "ST": 175},
        "primary_source_url": "https://www.ibps.in/",
        "raw_notification_text": "IBPS Clerk. Graduation. Age 20-28.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "SSC CGL 2026 Mains (Tier-II)",
        "org_name": "Staff Selection Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "SSC",
        "education_required": ["Any Graduate", "Graduate"],
        "age_min": 18,
        "age_max": 32,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 8, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "prerequisite_exams": [{"exam": "SSC CGL Prelims", "year_validity": "same year"}],
        "apply_end_date": date(2026, 11, 30),
        "exam_date": date(2026, 12, 20),
        "exam_stage": "Mains",
        "status": "Upcoming",
        "primary_source_url": "https://ssc.gov.in/",
        "raw_notification_text": "SSC CGL Tier-II for candidates who clear Tier-I.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "RBI Grade B Officers 2026",
        "org_name": "Reserve Bank of India",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Banking",
        "education_required": ["Graduate", "Postgraduate", "Any Graduate"],
        "min_percentage": 60,
        "age_min": 21,
        "age_max": 30,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 5, 1),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "apply_start_date": date(2026, 5, 1),
        "apply_end_date": date(2026, 9, 12),
        "exam_stage": "Phase-I",
        "status": "ClosingSoon",
        "fee_structure": {"General": 850, "OBC": 850, "SC": 100, "ST": 100},
        "primary_source_url": "https://opportunities.rbi.org.in/",
        "raw_notification_text": "RBI Grade B. Minimum 60% in graduation. Age 21-30.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "NTA UGC-NET December 2026",
        "org_name": "National Testing Agency",
        "sector": "Govt",
        "opportunity_type": "Admission",
        "domain": "Teaching",
        "education_required": ["Postgraduate", "M.A.", "M.Sc", "M.Com", "M.Tech"],
        "min_percentage": 55,
        "age_min": None,
        "age_max": None,
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "apply_start_date": date(2026, 9, 1),
        "apply_end_date": date(2026, 10, 10),
        "exam_date": date(2026, 12, 15),
        "exam_stage": "Single-Stage",
        "status": "Upcoming",
        "fee_structure": {"General": 1150, "OBC": 600, "SC": 325, "ST": 325},
        "primary_source_url": "https://ugcnet.nta.ac.in/",
        "raw_notification_text": "UGC NET. Master's degree with 55% (50% for reserved categories).",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "IOCL Graduate Engineer Trainee 2026",
        "org_name": "Indian Oil Corporation Limited",
        "sector": "PSU",
        "opportunity_type": "Job",
        "domain": "Engineering",
        "education_required": ["B.Tech", "B.E."],
        "stream_required": ["Computer Science", "IT", "Electrical", "Mechanical", "Chemical"],
        "min_percentage": 65,
        "age_min": 18,
        "age_max": 26,
        "age_relaxation_rules": {"OBC": 3, "SC": 5, "ST": 5},
        "age_cutoff_date": date(2026, 6, 30),
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "apply_start_date": date(2026, 8, 1),
        "apply_end_date": date(2026, 9, 22),
        "exam_stage": "GATE",
        "status": "ApplicationsOpen",
        "fee_structure": {"General": 0, "OBC": 0, "SC": 0, "ST": 0},
        "primary_source_url": "https://iocl.com/latest-job-opening",
        "raw_notification_text": "IOCL GET through GATE. B.E./B.Tech in specified branches. 65% marks.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "Software Engineer — FinTech (sample private listing)",
        "org_name": "Example FinServe Pvt Ltd",
        "sector": "Private",
        "opportunity_type": "Job",
        "domain": "Engineering",
        "education_required": ["B.Tech", "B.E.", "M.Tech"],
        "stream_required": ["Computer Science", "IT"],
        "age_min": 21,
        "age_max": 32,
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "experience_required_years": 1,
        "apply_start_date": date(2026, 8, 15),
        "apply_end_date": date(2026, 10, 1),
        "status": "ApplicationsOpen",
        "primary_source_url": "https://www.naukri.com/",
        "raw_notification_text": "Sample private-sector listing for schema validation. 1 year experience.",
        "reviewed_by_human": True,
        "published": True,
    },
    {
        "canonical_title": "Delhi Police Constable 2026 (draft — awaiting QA)",
        "org_name": "Staff Selection Commission",
        "sector": "Govt",
        "opportunity_type": "Job",
        "domain": "Police",
        "education_required": None,
        "age_min": 18,
        "age_max": None,
        "gender_restriction": "Any",
        "domicile_required": "Any",
        "physical_standards": {"height_male_cm": 170, "height_female_cm": 157},
        "apply_end_date": date(2026, 10, 5),
        "status": "Upcoming",
        "primary_source_url": "https://ssc.gov.in/",
        "raw_notification_text": "Draft extraction missing age_max and education — must stay in QA queue.",
        "extraction_confidence": 0.3,
        "reviewed_by_human": False,
        "published": False,
    },
]


def run():
    Base.metadata.create_all(bind=engine)
    db = SessionLocal()
    try:
        if db.query(Opportunity).count() > 0:
            print("Opportunities already present; skip seed.")
            return
        for row in SEED:
            db.add(Opportunity(**row))
        db.commit()
        print(f"Seeded {len(SEED)} opportunities.")
    finally:
        db.close()


if __name__ == "__main__":
    run()
